### ISSUE TITLE
ReadMe File Needed

### ISSUE THREAD

**Issue by sKSama** [sKSama/Car-Detection-Basic-Open-CV#1]
Please Update the readme file and Keep the video link in it, do no delete.

**Comment by sam4t** [comment]
what exactly should be changed ?

**Comment by frbio** [comment]
Brief me with the details. I can work on this.

**Comment by sKSama** [comment]
> Brief me with the details. I can work on this.

> what exactly should be changed ?


Just Add about basics of OpenCV and Haarcascade
Add About installation of openCV (command)
Keep the Video Link somewhere on the top
A pic about Car detection showing the project will be appreciated

**Comment by iriyagupta** [comment]
@sKSama Hi i would like to work on this

**Comment by sKSama** [comment]
> @sKSama Hi i would like to work on this

this issue is open to all, you can work on it and send me a PR i will merge it

**Comment by SarthakRana** [comment]
Hi @sKSama . I would like to work on this issue.

**Comment by Srinjoycode** [comment]
Sir, I have added a picture representation of car detection and made some useful modification to the file , please could you merge my pull request
